### PR TITLE
[RemoveLayoutConversions] Fix reduce failed infer type error

### LINKED ISSUE #364: argmax tl.reduce gives `error: 'tt.reduce' op failed to infer returned types`
@jayfurmanek @zhanglx13 @binarman 
cc: @dllehr-amd @jithunnair-amd 

With TOT triton we are seeing a UT regression in PyTorch.

I have confirmed the change that caused the breakage came in during ifu230908-2 and last known working commit is https://github.com/ROCmSoftwarePlatform/triton/commit/287b0adcc2a9607b326a0cda18388dd221c386c2

The UTs failing in `test_torchinductor.py` are all argmax related
```
CudaTests.test_argmax_argmin2_cuda
CudaTests.test_argmax_argmin_with_nan_cuda
CudaTests.test_reduction4_cuda
```

I have developed a reproducer that passes on NVIDIA platform with latest triton (29828fe), fails on TOT triton-mlir and passes on triton-mlir at commit https://github.com/ROCmSoftwarePlatform/triton/commit/287b0adcc2a9607b326a0cda18388dd221c386c2.

Note: the failure occurs on the store after the `max_with_index` reduction.
`return tl.reduce((value, index), dim, maximum_with_index)`

**Reproducer**
```
import torch
import triton
import triton.language as tl

@triton.jit
def min_with_index(value, index, dim):
    return tl.reduce((value, index), dim, minimum_with_index)

@triton.jit
def max_with_index(value, index, dim):
    return tl.reduce((value, index), dim, maximum_with_index)

@triton.jit
def promote_to_tensor(x):
    # Addition promotes to tensor for us
    return x + tl.zeros((1,), tl.int1)

@triton.jit
def is_floating(x):
    return promote_to_tensor(x).dtype.is_floating()

@triton.jit
def maximum_with_index(a_value, a_index, b_value, b_index):
    mask = a_value > b_value
    equal = a_value == b_value
    if is_floating(a_value):
        a_isnan = a_value != a_value
        b_isnan = b_value != b_value
        mask |= a_isnan and not b_isnan
        # Consider NaNs as equal
        equal |= a_isnan and b_isnan

    # Prefer lowest index if values are equal
    mask |= equal & (a_index < b_index)
    return tl.where(mask, a_value, b_value), tl.where(mask, a_index, b_index)

@triton.jit
def minimum_with_index(a_value, a_index, b_value, b_index):
    mask = a_value < b_value
    equal = a_value == b_value
    if is_floating(a_value):
        a_isnan = a_value != a_value
        b_isnan = b_value != b_value
        mask |= a_isnan and not b_isnan
        # Consider NaNs as equal
        equal |= a_isnan and b_isnan

    # Prefer lowest index if values are equal
    mask |= equal & (a_index < b_index)
    return tl.where(mask, a_value, b_value), tl.where(mask, a_index, b_index)

@triton.jit
def triton_kernel(in_ptr0, out_ptr0, out_ptr1, xnumel, rnumel, XBLOCK : tl.constexpr, RBLOCK : tl.constexpr):
    xnumel = 144
    rnumel = 144
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:, None]
    xmask = xindex < xnumel
    rbase = tl.arange(0, RBLOCK)[None, :]
    x0 = xindex
    _tmp2 = tl.full([XBLOCK, RBLOCK], float("-inf"), tl.float32)
    _tmp2_index = tl.full([XBLOCK, RBLOCK], 9223372036854775807, tl.int64)
    _tmp3 = tl.full([XBLOCK, RBLOCK], float("inf"), tl.float32)
    _tmp3_index = tl.full([XBLOCK, RBLOCK], 9223372036854775807, tl.int64)
    for roffset in range(0, rnumel, RBLOCK):
        rindex = roffset + rbase
        rmask = rindex < rnumel
        r1 = rindex
        tmp0 = tl.load(in_ptr0 + (x0 + (144*r1)), rmask & xmask, eviction_policy='evict_first', other=0).to(tl.float32)
        tmp1 = tl.broadcast_to(tmp0, [XBLOCK, RBLOCK])
        _tmp2_next, _tmp2_index_next = maximum_with_index(
            _tmp2, _tmp2_index, tmp1, rindex
        )
        _tmp2 = tl.where(rmask & xmask, _tmp2_next, _tmp2)
        _tmp2_index = tl.where(rmask & xmask, _tmp2_index_next, _tmp2_index)
        _tmp3_next, _tmp3_index_next = minimum_with_index(
            _tmp3, _tmp3_index, tmp1, rindex
        )
        _tmp3 = tl.where(rmask & xmask, _tmp3_next, _tmp3)
        _tmp3_index = tl.where(rmask & xmask, _tmp3_index_next, _tmp3_index)
    _, tmp2_tmp = max_with_index(_tmp2, _tmp2_index, 1)
    tmp2 = tmp2_tmp[:, None]
    tl.store(out_ptr0 + (x0), tmp2, xmask)

arg0_1 = torch.rand((144, 144), device='cuda:0', dtype=torch.float16)
buf0 = torch.empty((144, ), device='cuda', dtype=torch.int64)
buf1 = torch.empty((144, ), device='cuda', dtype=torch.int64)
xnumel = 144
rnumel = 144

# Launch the triton kernel without async compile
triton_kernel[(144,)](arg0_1, buf0, buf1, 144, 144, 256, 256)
```

Full error log:
```
loc(callsite("kernel.py":13:42 at "kernel.py":83:53)): error: 'tt.reduce' op inferred type(s) 'tensor<256xf32, #triton_gpu.slice<{dim = 1, parent = #triton_gpu.blocked<{sizePerThread = [1, 1], threadsPerWarp = [64, 1], warpsPerCTA = [4, 1], order = [0, 1], CTAsPerCGA = [1, 1], CTASplitNum = [1, 1], CTAOrder = [0, 1]}>}>>', 'tensor<256xi64, #triton_gpu.slice<{dim = 1, parent = #triton_gpu.blocked<{sizePerThread = [1, 1], threadsPerWarp = [64, 1], warpsPerCTA = [4, 1], order = [0, 1], CTAsPerCGA = [1, 1], CTASplitNum = [1, 1], CTAOrder = [0, 1]}>}>>' are incompatible with return type(s) of operation 'tensor<256xf32, #triton_gpu.slice<{dim = 1, parent = #triton_gpu.blocked<{sizePerThread = [8, 1], threadsPerWarp = [32, 2], warpsPerCTA = [1, 4], order = [0, 1], CTAsPerCGA = [1, 1], CTASplitNum = [1, 1], CTAOrder = [0, 1]}>}>>', 'tensor<256xi64, #triton_gpu.slice<{dim = 1, parent = #triton_gpu.blocked<{sizePerThread = [1, 1], threadsPerWarp = [64, 1], warpsPerCTA = [4, 1], order = [0, 1], CTAsPerCGA = [1, 1], CTASplitNum = [1, 1], CTAOrder = [0, 1]}>}>>'
loc(callsite("kernel.py":13:42 at "kernel.py":83:53)): error: 'tt.reduce' op failed to infer returned types
Traceback (most recent call last):
  File "kernel.py", line 95, in <module>
    triton_kernel[(144,)](arg0_1, buf0, buf1, 144, 144, 256, 256)
  File "<string>", line 74, in triton_kernel
  File "/root/triton/python/triton/compiler/compiler.py", line 607, in compile
    next_module = compile_kernel(module)
  File "/root/triton/python/triton/compiler/compiler.py", line 507, in <lambda>
    lambda src: optimize_ttgir(ttir_to_ttgir(src, num_warps, warp_size, num_ctas, arch), num_stages, num_warps, num_ctas, arch, cluster_info, enable_warp_specialization, enable_persistent, optimize_epilogue))
  File "/root/triton/python/triton/compiler/compiler.py", line 154, in optimize_ttgir
    pm.run(mod)
```

### PR DESCRIPTION
**Pull request by binarman**
This PR fixes layout propagation algorithm in RemoveLayoutConversions pass. In some cases during rewriteSlice process, reduce operation with multiple outputs rewrites only one output layout, which breaks assumption that both outputs should have same layout.

This change is a minimal part of https://github.com/openai/triton/pull/2331 change and small lit test for regression testing.

Fixes #364

### CODE REVIEW

File: lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp [hunk 1]
```diff
@@ -1013,9 +1013,16 @@ static void hoistConvertOnTopOfExt(ConvertLayoutOp convertOp) {
...
+#ifndef USE_ROCM
   auto isExtOp = [](Operation *op) {
     return isa<arith::ExtSIOp, arith::ExtUIOp, arith::ExtFOp>(op);
   };
+#else
+  auto isExtOp = [](Operation *op) {
+    return isa<arith::ExtSIOp, arith::ExtUIOp, arith::ExtFOp,
+              triton::BroadcastOp, triton::ExpandDimsOp>(op);
+  };
+#endif
```
Comment (alefimov-amd) [inline lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp:1025]: This part is changed multiple times between our current and previous IFU.
I wrapped it with `USE_ROCM` to highlight it in case this PR is merged before ongoing IFU

File: lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp [hunk 2]
```diff
@@ -1053,12 +1060,14 @@ static void hoistConvertOnTopOfExt(ConvertLayoutOp convertOp) {
...
     return;
+  std::optional<Attribute> srcEncoding =
+       inferSrcEncoding(extOp, layout[extOp->getResult(0)]);
   // Move the convert before the ext op and rewrite the slice.
   OpBuilder builder(extOp);
   auto tensorType = extOp->getOperand(0).getType().cast<RankedTensorType>();
   auto newType =
       RankedTensorType::get(tensorType.getShape(), tensorType.getElementType(),
-                            layout[extOp->getResult(0)]);
+                            *srcEncoding);
```
Comment (alefimov-amd) [inline lib/Dialect/TritonGPU/Transforms/RemoveLayoutConversions.cpp:1070]: This part changed in upstream only once (and looks exactly the same), so it should not induct any problems on merge or rebase on top of upstream changes.

**Comment by alefimov-amd** [comment]
For the record, description of the problem here:
Error was in an optimization that moved layout conversion on top of "extension" operation to reduce LDS usage (smaller type, smaller scratch buffers we need to convert layouts).

Consider this example as input:
```
%0 = ...
%1 = ..
%2 = arith.extf %1
%3 = tt.reduce %0, %1  // %3 contains two outputs
%4 = tt.expand_dims %3#1 // expand dims takes second output of reduce op
%5 = triton_gpu.convert_layout %4
```

before this change, optimizations moved layout conversion before `%2` extf operation, rewriting layouts of all values along data flow path. Unfortunately it did not rewrite layout of first output of reduce operation, which broke assumption that layouts of this reduce operations should be equal.

With this change, layout conversions is moved only before `%4` expand_dim operation.
This is achieved by change in stop condition of algorithm and fix in target layout computation algorithm.

File: test/TritonGPU/combine.mlir [hunk 3]
```diff
@@ -1172,10 +1172,12 @@ module attributes {"triton_gpu.num-warps" = 2 : i32} {
 
 // CHECK-LABEL: reduce_cvt2
 // Match the reduction
+// CHECK-NOT: triton_gpu.convert_layout
 // CHECK: tt.reduce
 // CHECK-SAME: axis = 1
-// CHECK: (tensor<1x256xf32, #blocked>) -> tensor<1xf32, #triton_gpu.slice<{dim = 1, parent = #blocked}>>
+// CHECK: (tensor<1x256xf32, #{{.*}}>) -> tensor<1xf32, #triton_gpu.slice<{dim = 1, parent = #{{.*}}}>>
 // CHECK: triton_gpu.convert_layout
+// CHECK: tt.expand_dims
```
Comment (alefimov-amd) [inline test/TritonGPU/combine.mlir:1180]: This change is also part of upstream changes

**Comment by jataylo** [comment]
With this PR I can confirm the argmax unit tests and previous reproducer now pass.

But this change seems to have caused a failure for us in another unit test 
```
test_torchinductor.py::CudaTests::test_batch_norm_2d_2_cuda loc("/tmp/torchinductor_root/5m/c5mbigghp7pzp26f4zncmescmhh3tgebh2yix7l2u3fog5rzai4j.py":16:23): error: ExpandDimsOp operand encoding must be SliceEncodingAttr
loc("/tmp/torchinductor_root/5m/c5mbigghp7pzp26f4zncmescmhh3tgebh2yix7l2u3fog5rzai4j.py":16:23): error: failed to infer layout for ExpandDimsOp
loc("/tmp/torchinductor_root/5m/c5mbigghp7pzp26f4zncmescmhh3tgebh2yix7l2u3fog5rzai4j.py":16:23): error: 'tt.expand_dims' op failed to infer returned types
FAILED [1.2648s]       
```

@alefimov-amd  let me know if you want me to get together a reproducer for this new issue.

**Review by jataylo — APPROVED** [review]
LGTM. Our core UTs and noted failing cases are passing after this change.
